### ISSUE TITLE
`--dry-run` with diff

### ISSUE THREAD

**Issue by gegoune** [tummychow/git-absorb#130]
Thanks for git-absorb, it has become critical tool in my daily workflow.

I have found myself absorbing somewhat large change sets recently but unfortunately having all changes staged and absorbed led to broken commits (broken in a way that checking out fixed up commits would lead to non-working code, that in itself is not git-absorb's fault really). I then have wished there was an `--diff` flag that could go along with `--dry-run` showing which changes would be part of which commit created by git-absorb. I then could potentially unstage some changes to adjust output. As of now, there is no way of knowing exactly what will end up where based on `--dry-run` alone.

Do you think that's feasible at all?

**Comment by jankatins** [comment]
Maybe a workaround and in case this is to hard to preview: I had similar (rare) experience and switched to always look at the generated commits in a GUI (girl taken in my case). If the commits are not good, I either rename the commit message or 'git reset --soft' back to the last sane commit.


For me, to make a preview worthwhile, it would need basically the same as I need to compare/ link commits with their reference commits. Just a diff would not be enough for me to judge if the whole series is sane. E.g. if I make a change to a line in two commits (implement+refactor), the fix-up might end up in the wrong commit. Orr the reverse: doing a refactor which touches code and then a otherwise isolated code change needs changes in the refactored code. I've now a fixup command where I use fzf to select a commit and generate a fix-up commit for that commit with the current staged changes.

**Comment by tummychow** [comment]
yeah i don't think this is practical. you're asking to print out every hunk, it's going to be a giant wall of text. this is yet another reason that git absorb supports being run without rebase. after doing that, you can git log -p to figure out what went where (or, if you also want to compare to the commits being absorbed into, reach for your git ui of choice as janatkins suggests)
