### ISSUE TITLE
Request: Allow fixing up past merge commits

### ISSUE THREAD

**Issue by CervEdin** [tummychow/git-absorb#134]
Similar to how you can force fixups on other authors, I would like to be able to absorb commits past merge commits.

If the user is using `--force` I think it's fair to assume that the user knows what they are doing and the walk of refs shouldn't be aborted just because there is a merge commit. And/or there should be a flag or option to enable walking past merges.

Is the current implementation because of limitations of the ref walking? Or to prevent users from messing up their main branch? Or both?

**Comment by CervEdin** [comment]
Looks like if

```
        if commit.parents().len() > 1 {
            warn!(logger, "Will not fix up past the merge commit"; "commit" => commit.id().to_string());
            break;
        }
```

is ignored, the fixup will happen on the merge commit. I'm guessing this is because there's no walk of the refs of the other parent? What I would want in a situation like this is to keep walking the commits of all parents and fixup the appropriate commit

**Comment by tummychow** [comment]
there's a lot more to this than just taking out that break.

- the loop for stack traversal and commutation needs to be overhauled to traverse a tree. this, alone, is already enough complexity that it would make me say no
- git rebase does not support traversing multiple parents. so you're also asking to reimplement the entirety of interactive rebases. (and even if you only want to do one parent, it's still a problem, because git rebase does not replay merge conflicts, so if you rebase through a merge, you have to resolve each conflict manually again)
- the concept of patch commutation becomes confused once you have multiple parents. what if a patch fails to commute with a commit on each of the branches? now it's ambiguous which of them it should be absorbed into
- more generally, git's definition of a merge conflict isn't quite the same as the patch theory concept of commutation. modifying a pre-merge commit might introduce a conflict that didn't previously exist

**Comment by CervEdin** [comment]
> the loop for stack traversal and commutation needs to be overhauled to traverse a tree.

Yes, I noticed that when I started poking around.

Not sure I follow this point

> git rebase does not support traversing multiple parents. so you're also asking to reimplement the entirety of interactive rebases.

are you referring to how `git-absorb` does an interactive rebase? I don't use that feature so I'm not familiar with it but it's not a problem to fixup past a merge using `git rebase` per se, I frequently do.

> (and even if you only want to do one parent, it's still a problem, because git rebase does not replay merge conflicts, so if you rebase through a merge, you have to resolve each conflict manually again)

It's true conflicts need to be re-resolved, but for my use case this is not an issue.

> the concept of patch commutation becomes confused once you have multiple parents. what if a patch fails to commute with a commit on each of the branches? now it's ambiguous which of them it should be absorbed into

Depends on the parents. For example, it's not ambiguous if there are two parents and one parent is an ancestor of the other.

I understand the complexity and concerns here.
That said, this limitation doesn’t impact my use case, and I think this could still be a valuable feature for certain workflows.
Would the project be open to reviewing contributions that attempt to implement this behavior?
Or is it outside the scope of interest entirely?

**Comment by tummychow** [comment]
this is a feature i would not accept. the only version i would _consider_ accepting is "one parent explicitly specified by the user on a merge with no conflicts", and even then i think there's correctness problems
