### ISSUE TITLE
Compare the index before & after git-absorb ran

### ISSUE THREAD

**Issue by est31** [tummychow/git-absorb#7]
It would be good to have git-absorb execute a sanity check by running `git write-tree` before it runs, then after it ran a second time. Optimally, the two values are the same. If they aren't the same, it should output an error.

**Comment by tummychow** [comment]
i don't think this works the way you describe. git-write-tree will result in the same tree object both before and after git-absorb runs, because the index tree doesn't get changed. what changes is the HEAD commit underneath the index, so the diff between those things changes after running git-absorb, but validating that as a sanity check is quite a bit trickier

in either case i think the real solution is to write tests and i just haven't written any
