### ISSUE TITLE
"Inverse" git aborb?

### ISSUE THREAD

**Issue by devinrhode2** [tummychow/git-absorb#86]
Let's say a questionable PR was merged in order to hit a deadline for a demo.

However, that code has since been completely re-written.

Of course I can branch off master, revert the PR/commits, and then base the re-written work on top of that.
However, I'd like to avoid the wholesale initial revert.

How can I make the initial revert "absorb" UP into the subsequent commiits?

Answer?

Enter interactive rebase
Drop the revert commit
Favor re-written code in every conflict (could use --strategy-option)
Check final diff, cleanup anything at the end (revert more) if needed

**Comment by tummychow** [comment]
i'm not sure i fully understand the question. let me try saying it back to you:

- i had an old pr
- that pr was merged into master
- i have a new pr, which happens to be a total rewrite of the old pr
- this pr is branched off master, but prior to the merge of the old pr

so the branch structure looks something like this:

```
old PR <- current master
|
C - new PR <- my current branch
|
B
|
A
```

i want to revert the old PR on your branch, so that it would look something like this:

```
new PR <- my branch
|
revert of old PR
|
old PR <- current master
|
C
|
B
|
A
```

but i don't want the revert to be a single commit, i want it to be absorbed into the commit(s) of my new PR. is this understanding correct? a rough sketch of how this could be done:

- for each hunk of each commit of my new PR, i find which hunk(s) in the revert commit do not commute with it. this produces a many-to-many mapping of commits in my new PR to hunks in the revert commit. (a commit in my new PR maps to a hunk in the revert commit if any hunk of the former fails to commute with the latter.)
- now i disambiguate the mapping by topographical order of commits. each hunk in the revert commit maps to the earliest commit in my new PR that fails to commute with it.
- for each commit in my new PR, i take all the hunks in the revert that fail to commute with it, and split them into a new commit. note that some hunks might be left in the revert that commute with all my new commits; those ones have to stay where they are. (so the branch structure might look like `... C - old PR - revert commit with all commuting hunks - revert commit with hunks for commit X1 - revert commit with hunks for commit X2 - new PR commit X1 - new PR commit X2` etc)
- now i modify the commit message of each commit in the _new PR_ to fixup back into the revert commit corresponding to it. so `new PR commit X1` would become `fixup! revert commit with hunks for commit X1` and so on.
- finally i can run an interactive rebase.

i'm going to be honest with you, this sounds quite unpleasant to implement. it does reuse some existing git-absorb machinery, but it also demands a lot of new machinery that git-absorb doesn't currently need. in particular, splitting a commit that's beneath a bunch of other commits is quite fiddly work. it essentially requires us to reimplement most of the functionality of an interactive rebase. this is much harder than what git-absorb currently has to do, which is simply creating new commits on the top of the stack.

furthermore, the use case seems very niche. i mentioned before (https://github.com/tummychow/git-absorb/issues/44#issuecomment-851106623) that i'm open to plumbing flags on git-absorb to query commutation (which would be useful for the first bullet point of the described algorithm). i think anything more than that would be a tough sell for me. we''re talking about a lot of code for something that's pretty rare. if i was in this situation, i would just leave the revert in one commit and move on... the new PR might even be easier to review that way.

**Comment by rjmunro** [comment]
You could maybe do something like:

* Revert all your commits with `git revert [base]..HEAD`
* Run absorb on the reverted commits
* Revert them all again
* Rebase `--onto [base]` to get rid of your original working and reverts, leaving only the reverted absorbed reverts

This may or may not achieve exactly what you want, but even if it works double revert will mess up the commit message - I'm not sure if there is a good way to fix that, there may be a way using revert's `--no-commit` option and committing with`-m`, but then you'd need to run in a loop rather than use revert's ability to undo multiple commits.

**Comment by devinrhode2** [comment]
I think the general solution is to get everyone on a team creating small
commits which are easy to revert or otherwise discard.

Agreed this is not worth the effort.
